### ISSUE TITLE
Visuaalinen editori

### ISSUE THREAD

**Issue by jay-jay-s** [kosmosnautti/ha-fmi-radar#1]
Visuaalinen editori ei näytä muokkauskenttiä. Ainoastaan yaml-editorilla voi muokata kortin sisältöä.

HA versiotiedot:
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Käyttöliittymä 20231208.2

**Comment by kosmosnautti** [comment]
Päivittelin koodia, visuaalisen editorin pitäisi olla taas kunnossa.
